# Generated by Django 4.0.5 on 2022-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_connected_device_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='site',
            name='elevation',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Elevation in meters'),
        ),
        migrations.AlterField(
            model_name='site',
            name='geolat',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude in Decimal Degrees'),
        ),
        migrations.AlterField(
            model_name='site',
            name='geolong',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude in Decimal Degrees'),
        ),
    ]
