# Generated by Django 4.0.5 on 2022-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_ip_address_alter_site_elevation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_site_name'),
        ),
    ]
