# Generated by Django 4.0.5 on 2022-07-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_site_unique_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_site', to='devices.site'),
        ),
    ]
