# Generated by Django 4.0.5 on 2023-04-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devicetype',
            field=models.CharField(choices=[('camera', 'camera'), ('covercalibrator', 'covercalibrator'), ('dome', 'dome'), ('filterwheel', 'filterwheel'), ('focuser', 'focuser'), ('observingconditions', 'observingconditions'), ('rotator', 'rotator'), ('safteymonitor', 'safetymonitor'), ('site', 'site'), ('switch', 'switch'), ('telescope', 'telescope')], max_length=20, null=True, verbose_name='Device Type'),
        ),
    ]
