from django.db import models

from .device import Device


class Camera(models.Model):
    device = models.ForeignKey(
        'Device',
        on_delete=models.CASCADE,
    )
    bayeroffsetx = models.IntegerField()
    bayeroffsety = models.IntegerField()
    binx = models.IntegerField()
    biny = models.IntegerField()
    camerastate = models.IntegerField()
    cameraxsize = models.IntegerField()
    cameraysize = models.IntegerField()
    canabortexposure = models.BooleanField()
    canasymmetricbin = models.BooleanField()
    canfastreadout = models.BooleanField()
    cangetcoolerpower = models.BooleanField()
    canpulseguide = models.BooleanField()
    cansetccdtemperature = models.BooleanField()
    canstopexposure = models.BooleanField()
    ccdtemperature = models.DecimalField(max_digits=5, decimal_places=2)
    cooleron = models.BooleanField()
    coolerpower = models.DecimalField(max_digits=5, decimal_places=2)
    electronsperadu = models.DecimalField(max_digits=5, decimal_places=2)
    exposuremax = models.DecimalField(max_digits=5, decimal_places=2)
    exposuremin = models.DecimalField(max_digits=5, decimal_places=2)
    exposureresolution = models.DecimalField(max_digits=5, decimal_places=2)
    fastreadout = models.BooleanField()
    fullwellcapacity = models.DecimalField(max_digits=5, decimal_places=2)
    gain = models.IntegerField()
    gainmax = models.IntegerField()
    gainmin = models.IntegerField()
    gains = models.JSONField()
    hasshutter = models.BooleanField()
    heatsinktemperature = models.DecimalField(max_digits=5, decimal_places=2)
    imagearray = models.JSONField()
    imagearrayvariant = models.JSONField()
    imageready = models.BooleanField()
    ispulseguiding = models.BooleanField()
    lastexposureduration = models.DecimalField(max_digits=5, decimal_places=2)
    lastexposurestarttime = models.CharField(max_length=255)
    maxadu = models.IntegerField()
    maxbinx = models.IntegerField()
    maxbiny = models.IntegerField()
    numx = models.IntegerField()
    numy = models.IntegerField()
    offset = models.IntegerField()
    offsetmax = models.IntegerField()
    offsetmin = models.IntegerField()
    offsets = models.JSONField()
    percentcompleted = models.IntegerField()
    pixelsizex = models.DecimalField(max_digits=5, decimal_places=2)
    pixelsizey = models.DecimalField(max_digits=5, decimal_places=2)
    readoutmode = models.IntegerField()
    readoutmodes = models.JSONField()
    sensorname = models.CharField(max_length=255)
    sensortype = models.IntegerField()
    setccdtemperature = models.DecimalField(max_digits=5, decimal_places=2)
    startx = models.IntegerField()
    starty = models.IntegerField()
    subexposureduration = models.DecimalField(max_digits=5, decimal_places=2)

