from django.db import models

from .device import Device

class Telescope(models.Model):
    device = models.ForeignKey(
        'Device',
        on_delete=models.CASCADE,
        )
    alignmentmode = models.IntegerField()
    altitude = models.DecimalField(max_digits=5, decimal_places=2)
    aperturearea = models.DecimalField(max_digits=5, decimal_places=2)
    aperturediameter = models.DecimalField(max_digits=5, decimal_places=2)
    athome = models.BooleanField()
    atpark = models.BooleanField()
    azimuth = models.DecimalField(max_digits=5, decimal_places=2)
    canfindhome = models.BooleanField()
    canpark = models.BooleanField()
    canpulseguide = models.BooleanField()
    cansetdeclinationrate = models.BooleanField()
    cansetguiderates = models.BooleanField()
    cansetpark = models.BooleanField()
    cansetpierside = models.BooleanField()
    cansetrightascensionrate = models.BooleanField()
    cansettracking = models.BooleanField()
    canslew = models.BooleanField()
    canslewaltaz = models.BooleanField()
    canslewaltazasync = models.BooleanField()
    canslewasync = models.BooleanField()
    cansync = models.BooleanField()
    cansyncaltaz = models.BooleanField()
    canunpark = models.BooleanField()
    declination = models.DecimalField(max_digits=5, decimal_places=2)
    declinationrate = models.DecimalField(max_digits=5, decimal_places=2)
    doesrefraction = models.BooleanField()
    equatorialsystem = models.IntegerField()
    focallength = models.DecimalField(max_digits=5, decimal_places=2)
    guideratedeclination = models.DecimalField(max_digits=5, decimal_places=2)
    guideraterightascension = models.DecimalField(max_digits=5, decimal_places=2)
    ispulseguiding = models.BooleanField()
    rightascension = models.DecimalField(max_digits=5, decimal_places=2)
    rightascensionrate = models.DecimalField(max_digits=5, decimal_places=2)
    sideofpier = models.IntegerField()
    siderealtime = models.DecimalField(max_digits=5, decimal_places=2)
    siteelevation = models.DecimalField(max_digits=5, decimal_places=2)
    sitelatitude = models.DecimalField(max_digits=5, decimal_places=2)
    sitelongitude = models.DecimalField(max_digits=5, decimal_places=2)
    slewing = models.BooleanField()
    slewsettletime = models.IntegerField()
    targetdeclination = models.DecimalField(max_digits=5, decimal_places=2)
    targetrightascension = models.DecimalField(max_digits=5, decimal_places=2)
    tracking = models.BooleanField()
    trackingrate = models.IntegerField()
    trackingrates = models.JSONField()
    utcdate = models.CharField(max_length=255)
    axisrates = models.JSONField()
    canmoveaxis = models.BooleanField()
    destinationsideofpier = models.IntegerField()

