# Generated by Django 4.0.5 on 2023-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_event_date_event_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_datetime',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
