# Generated by Django 4.0.5 on 2023-02-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('scheduler', '0003_alter_event_event_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='routine',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='routines.routine'),
            preserve_default=False,
        ),
    ]
