# Generated by Django 4.0.5 on 2023-02-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_port'),
        ('routines', '0001_initial'),
        ('scheduler', '0005_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.routine'),
        ),
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.site'),
        ),
    ]
