# Generated by Django 4.0.5 on 2023-02-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_category_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
