# Generated by Django 4.0.5 on 2023-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10, null=True, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='event',
            name='interval',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Interval'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
