# Generated by Django 4.0.5 on 2023-03-09 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_event_frequency_event_interval_event_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occurences',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Occurences (1-100)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], max_length=10, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Interval (1-100)'),
        ),
    ]
