# Generated by Django 4.0.5 on 2023-03-30 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_event_occurences_alter_event_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Interval (1-100)')),
                ('timeunit', models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], max_length=10, null=True, verbose_name='Unit of Time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.event')),
            ],
        ),
    ]
